@include('dashboard.admin.includes.head')
@include('dashboard.admin.includes.header')
@include('dashboard.admin.includes.aside-left')
@include('dashboard.admin.includes.aside-right')
@yield('content')
@include('dashboard.admin.includes.footer')
